version: '3'
services:
  web_dev:
    image: freeewind/axcessiom_web
    container_name: test
    build: .
    ports:
      - 4201:4200
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules